services:
  redis:
    image: redis:latest
    container_name: redis-container
    command: ["redis-server", "--requirepass", "userpw"]
    ports:
      - "6379:6379"
    networks:
      - redis_network

networks:
  redis_network:
    driver: bridge